import { Brain } from "../classes/Brain";
import type { Direction } from "../classes/Strategy";
import { Strategy } from "../classes/Strategy";
import { Board } from "../classes/Board";
import { Boats } from "../types/Boats";
import { State } from "../types/State";

/** Random bot that places boats randomly and picks targets at random. */
export class Random extends Brain {
  private myBoard: Board;
  private adversaryBoard: Board;
  private myStrategy: Strategy;
  private targetedCells: Set<string>;

  /** Initializes the bot with empty boards and generates a random boat placement strategy. */
  constructor() {
    super();
    this.myBoard = new Board();
    this.adversaryBoard = new Board();
    this.myStrategy = new Strategy();
    this.targetedCells = new Set();
    this.myStrategy = this.generateStrategy();
  }

  /** Returns the strategy generated by this bot. */
  getStrategy(): Strategy {
    return this.myStrategy;
  }

  /**
   * Generates a random valid placement for all four boat types.
   * Each boat is placed at a random position with a random direction, ensuring
   * it fits within the 11x11 board and does not overlap with other boats.
   * @returns A Strategy containing all boat placements.
   */
  private generateStrategy(): Strategy {
    const boatTypes = [
      Boats.AircraftCarrier,
      Boats.Cruiser,
      Boats.TorpedoBoat,
      Boats.Submarine,
    ];
    const directions: Direction[] = ["left", "right", "up", "down"];

    for (const boat of boatTypes) {
      let placed = false;
      while (!placed) {
        const x = Math.floor(Math.random() * 11);
        const y = Math.floor(Math.random() * 11);
        const direction = directions[Math.floor(Math.random() * 4)]!;
        const testCells = this.getCellsForBoat(boat, x, y, direction);

        const valid = testCells.every(
          (cell) =>
            cell.x >= 0 &&
            cell.x < 11 &&
            cell.y >= 0 &&
            cell.y < 11 &&
            !this.myStrategy.isHit(cell.x, cell.y),
        );

        if (valid) {
          this.myStrategy.addBoat(boat, x, y, direction);
          placed = true;
        }
      }
    }

    return this.myStrategy;
  }

  /**
   * Computes the cells occupied by a boat given its type, starting coordinates, and direction.
   * @param boat The type of boat.
   * @param x The starting x coordinate.
   * @param y The starting y coordinate.
   * @param direction The direction the boat extends.
   * @returns An array of coordinate objects.
   */
  private getCellsForBoat(
    boat: Boats,
    x: number,
    y: number,
    direction: Direction,
  ): { x: number; y: number }[] {
    const cells: { x: number; y: number }[] = [];
    for (let i = 0; i < boat; i++) {
      switch (direction) {
        case "right":
          cells.push({ x: x + i, y });
          break;
        case "left":
          cells.push({ x: x - i, y });
          break;
        case "down":
          cells.push({ x, y: y + i });
          break;
        case "up":
          cells.push({ x, y: y - i });
          break;
      }
    }
    return cells;
  }

  /**
   * Picks a random coordinate that has not been targeted before.
   * @returns An object with x and y coordinates.
   */
  think(): { x: number; y: number } {
    let x: number;
    let y: number;
    do {
      x = Math.floor(Math.random() * 11);
      y = Math.floor(Math.random() * 11);
    } while (this.targetedCells.has(`${x},${y}`));
    this.targetedCells.add(`${x},${y}`);
    return { x, y };
  }

  /**
   * Records the opponent's move. Checks the bot's own strategy to determine if the shot hit a boat.
   * @param x The x coordinate attacked by the opponent.
   * @param y The y coordinate attacked by the opponent.
   */
  turn(x: number, y: number): void {
    if (this.myStrategy.isHit(x, y)) {
      this.myBoard.board[x]![y] = State.Hit;
      const sunk = this.myStrategy.isSunk(this.myBoard.board);
      if (sunk) {
        for (const cell of this.myStrategy.getCells(sunk)) {
          this.myBoard.board[cell.x]![cell.y] = State.Sunk;
        }
      }
    }
  }

  /**
   * Returns the current knowledge of the adversary board.
   * @returns The adversary board tracked by this bot.
   */
  getAdversaryBoard(): Board {
    return this.adversaryBoard;
  }
}
