import { Brain } from "../classes/Brain";
import type { Direction } from "../classes/Strategy";
import { Strategy } from "../classes/Strategy";
import { Board } from "../classes/Board";
import { Boats } from "../types/Boats";
import { State } from "../types/State";

/**
 * Smart bot that places boats far apart from each other.
 * In hunt mode it targets random cells. Once it hits a ship it switches to target mode
 * and probes adjacent cells to sink the full boat.
 */
export class SmartBot extends Brain {
	private myBoard: Board;
	private myStrategy: Strategy;
	private targetedCells: Set<string>;
	private hitsToExplore: { x: number; y: number }[];
	private exploredHits: Set<string>;

	/** Initializes the bot with empty boards and generates a spread-out boat placement. */
	constructor() {
		super();
		this.name = "SmartBot";
		this.myBoard = new Board();
		this.myStrategy = new Strategy();
		this.targetedCells = new Set();
		this.hitsToExplore = [];
		this.exploredHits = new Set();
		this.myStrategy = this.generateStrategy();
	}

	/** Returns the strategy generated by this bot. */
	getStrategy(): Strategy {
		return this.myStrategy;
	}

	/**
	 * Generates a placement that spreads boats far from each other.
	 * Each new boat must be at least 2 cells away from all existing placements.
	 * @returns A Strategy containing all boat placements.
	 */
	private generateStrategy(): Strategy {
		const boatTypes = [
			Boats.AircraftCarrier,
			Boats.Cruiser,
			Boats.TorpedoBoat,
			Boats.Submarine,
		];
		const directions: Direction[] = ["left", "right", "up", "down"];

		for (const boat of boatTypes) {
			let placed = false;
			while (!placed) {
				const x = Math.floor(Math.random() * 11);
				const y = Math.floor(Math.random() * 11);
				const direction = directions[Math.floor(Math.random() * 4)]!;
				const testCells = this.getCellsForBoat(boat, x, y, direction);

				const valid = testCells.every(
					(cell) =>
						cell.x >= 0 &&
						cell.x < 11 &&
						cell.y >= 0 &&
						cell.y < 11 &&
						!this.myStrategy.isHit(cell.x, cell.y) &&
						this.isFarFromOthers(cell.x, cell.y)
				);

				if (valid) {
					this.myStrategy.addBoat(boat, x, y, direction);
					placed = true;
				}
			}
		}

		return this.myStrategy;
	}

	/**
	 * Checks that a cell is at least 2 cells away from every existing boat placement.
	 * @param x The x coordinate to check.
	 * @param y The y coordinate to check.
	 * @returns True if the cell is far enough from all placed boats.
	 */
	private isFarFromOthers(x: number, y: number): boolean {
		for (const placement of this.myStrategy.placements) {
			for (const cell of this.myStrategy.getCells(placement)) {
				if (Math.abs(cell.x - x) <= 1 && Math.abs(cell.y - y) <= 1) {
					return false;
				}
			}
		}
		return true;
	}

	/**
	 * Computes the cells occupied by a boat given its type, starting coordinates, and direction.
	 * @param boat The type of boat.
	 * @param x The starting x coordinate.
	 * @param y The starting y coordinate.
	 * @param direction The direction the boat extends.
	 * @returns An array of coordinate objects.
	 */
	private getCellsForBoat(
		boat: Boats,
		x: number,
		y: number,
		direction: Direction
	): { x: number; y: number }[] {
		const cells: { x: number; y: number }[] = [];
		for (let i = 0; i < boat; i++) {
			switch (direction) {
				case "right":
					cells.push({ x: x + i, y });
					break;
				case "left":
					cells.push({ x: x - i, y });
					break;
				case "down":
					cells.push({ x, y: y + i });
					break;
				case "up":
					cells.push({ x, y: y - i });
					break;
				default:
					break;
			}
		}
		return cells;
	}

	/**
	 * Decides the next coordinate to attack.
	 * If there are hot cells from a previous hit it targets them first.
	 * Otherwise it picks a random untargeted cell.
	 * @returns An object with x and y coordinates.
	 */
	think(): { x: number; y: number } {
		const board = this.getAdversaryBoard();

		for (let x = 0; x < 11; x++) {
			for (let y = 0; y < 11; y++) {
				if (
					board.board[x]![y] === State.Hit &&
					!this.exploredHits.has(`${x},${y}`)
				) {
					this.exploredHits.add(`${x},${y}`);
					this.addAdjacentCells(x, y);
				}
			}
		}

		while (this.hitsToExplore.length > 0) {
			const cell = this.hitsToExplore.shift()!;
			if (!this.targetedCells.has(`${cell.x},${cell.y}`)) {
				this.targetedCells.add(`${cell.x},${cell.y}`);
				return cell;
			}
		}

		let x: number;
		let y: number;
		do {
			x = Math.floor(Math.random() * 11);
			y = Math.floor(Math.random() * 11);
		} while (this.targetedCells.has(`${x},${y}`));
		this.targetedCells.add(`${x},${y}`);
		return { x, y };
	}

	/**
	 * Adds untargeted adjacent cells to the exploration queue.
	 * @param x The x coordinate of the hit cell.
	 * @param y The y coordinate of the hit cell.
	 */
	private addAdjacentCells(x: number, y: number): void {
		const neighbors = [
			{ x: x - 1, y },
			{ x: x + 1, y },
			{ x, y: y - 1 },
			{ x, y: y + 1 },
		];
		for (const cell of neighbors) {
			if (
				cell.x >= 0 &&
				cell.x < 11 &&
				cell.y >= 0 &&
				cell.y < 11 &&
				!this.targetedCells.has(`${cell.x},${cell.y}`) &&
				!this.hitsToExplore.some((c) => c.x === cell.x && c.y === cell.y)
			) {
				this.hitsToExplore.push(cell);
			}
		}
	}

	/**
	 * Records the opponent's move and updates the bot's own board.
	 * @param x The x coordinate attacked by the opponent.
	 * @param y The y coordinate attacked by the opponent.
	 */
	turn(x: number, y: number): void {
		if (this.myStrategy.isHit(x, y)) {
			this.myBoard.board[x]![y] = State.Hit;
			const sunk = this.myStrategy.isSunk(this.myBoard.board);
			if (sunk) {
				for (const cell of this.myStrategy.getCells(sunk)) {
					this.myBoard.board[cell.x]![cell.y] = State.Sunk;
				}
			}
		}
	}
}
