import { Brain } from "../classes/Brain";
import type { Direction } from "../classes/Strategy";
import { Strategy } from "../classes/Strategy";
import { Board } from "../classes/Board";
import { Boats } from "../types/Boats";
import { State } from "../types/State";

/**
 * Strategic bot that searches the board using a step 3 pattern (linear and diagonal).
 * Once it estimates it has found all boats it switches to systematic clean up.
 */
export class StrategicBot extends Brain {
  private myBoard: Board;
  private myStrategy: Strategy;
  private targetedCells: Set<string>;
  private searchQueue: { x: number; y: number }[];
  private hitsToExplore: { x: number; y: number }[];
  private exploredHits: Set<string>;
  private totalHitsFound: number;

  /** Initializes the bot with empty boards, generates a random placement, and builds the search pattern. */
  constructor() {
    super();
    this.myBoard = new Board();
    this.myStrategy = new Strategy();
    this.targetedCells = new Set();
    this.searchQueue = [];
    this.hitsToExplore = [];
    this.exploredHits = new Set();
    this.totalHitsFound = 0;
    this.myStrategy = this.generateStrategy();
    this.buildSearchPattern();
  }

  /** Returns the strategy generated by this bot. */
  getStrategy(): Strategy {
    return this.myStrategy;
  }

  /**
   * Generates a random valid placement for all four boat types.
   * @returns A Strategy containing all boat placements.
   */
  private generateStrategy(): Strategy {
    const boatTypes = [
      Boats.AircraftCarrier,
      Boats.Cruiser,
      Boats.TorpedoBoat,
      Boats.Submarine,
    ];
    const directions: Direction[] = ["left", "right", "up", "down"];

    for (const boat of boatTypes) {
      let placed = false;
      while (!placed) {
        const x = Math.floor(Math.random() * 11);
        const y = Math.floor(Math.random() * 11);
        const direction = directions[Math.floor(Math.random() * 4)]!;
        const testCells = this.getCellsForBoat(boat, x, y, direction);

        const valid = testCells.every(
          (cell) =>
            cell.x >= 0 &&
            cell.x < 11 &&
            cell.y >= 0 &&
            cell.y < 11 &&
            !this.myStrategy.isHit(cell.x, cell.y),
        );

        if (valid) {
          this.myStrategy.addBoat(boat, x, y, direction);
          placed = true;
        }
      }
    }

    return this.myStrategy;
  }

  /**
   * Builds a search pattern with step 3 targeting both linear and diagonal cells.
   * Linear: cells where both coordinates are multiples of 3.
   * Diagonal: cells where (x + y) is a multiple of 3 but not already covered linearly.
   */
  private buildSearchPattern(): void {
    for (let y = 0; y < 11; y += 3) {
      for (let x = 0; x < 11; x += 3) {
        this.searchQueue.push({ x, y });
      }
    }

    for (let y = 0; y < 11; y++) {
      for (let x = 0; x < 11; x++) {
        if ((x + y) % 3 === 0 && x % 3 !== 0 && y % 3 !== 0) {
          this.searchQueue.push({ x, y });
        }
      }
    }
  }

  /**
   * Computes the cells occupied by a boat given its type, starting coordinates, and direction.
   * @param boat The type of boat.
   * @param x The starting x coordinate.
   * @param y The starting y coordinate.
   * @param direction The direction the boat extends.
   * @returns An array of coordinate objects.
   */
  private getCellsForBoat(
    boat: Boats,
    x: number,
    y: number,
    direction: Direction,
  ): { x: number; y: number }[] {
    const cells: { x: number; y: number }[] = [];
    for (let i = 0; i < boat; i++) {
      switch (direction) {
        case "right":
          cells.push({ x: x + i, y });
          break;
        case "left":
          cells.push({ x: x - i, y });
          break;
        case "down":
          cells.push({ x, y: y + i });
          break;
        case "up":
          cells.push({ x, y: y - i });
          break;
      }
    }
    return cells;
  }

  /**
   * Decides the next coordinate to attack.
   * Follows the step 3 search pattern. When a hit is found it switches to target mode
   * to probe adjacent cells. Once all ships are located it continues cleanup via the search pattern.
   * @returns An object with x and y coordinates.
   */
  think(): { x: number; y: number } {
    const board = this.getAdversaryBoard();

    for (let x = 0; x < 11; x++) {
      for (let y = 0; y < 11; y++) {
        if (
          board.board[x]![y] === State.Hit &&
          !this.exploredHits.has(`${x},${y}`)
        ) {
          this.exploredHits.add(`${x},${y}`);
          this.totalHitsFound++;
          this.addAdjacentCells(x, y);
        }
      }
    }

    while (this.hitsToExplore.length > 0) {
      const cell = this.hitsToExplore.shift()!;
      if (!this.targetedCells.has(`${cell.x},${cell.y}`)) {
        this.targetedCells.add(`${cell.x},${cell.y}`);
        return cell;
      }
    }

    while (this.searchQueue.length > 0) {
      const cell = this.searchQueue.shift()!;
      if (!this.targetedCells.has(`${cell.x},${cell.y}`)) {
        this.targetedCells.add(`${cell.x},${cell.y}`);
        return cell;
      }
    }

    let x: number;
    let y: number;
    do {
      x = Math.floor(Math.random() * 11);
      y = Math.floor(Math.random() * 11);
    } while (this.targetedCells.has(`${x},${y}`));
    this.targetedCells.add(`${x},${y}`);
    return { x, y };
  }

  /**
   * Adds untargeted adjacent cells to the exploration queue.
   * @param x The x coordinate of the hit cell.
   * @param y The y coordinate of the hit cell.
   */
  private addAdjacentCells(x: number, y: number): void {
    const neighbors = [
      { x: x - 1, y },
      { x: x + 1, y },
      { x, y: y - 1 },
      { x, y: y + 1 },
    ];
    for (const cell of neighbors) {
      if (
        cell.x >= 0 &&
        cell.x < 11 &&
        cell.y >= 0 &&
        cell.y < 11 &&
        !this.targetedCells.has(`${cell.x},${cell.y}`) &&
        !this.hitsToExplore.some((c) => c.x === cell.x && c.y === cell.y)
      ) {
        this.hitsToExplore.push(cell);
      }
    }
  }

  /**
   * Records the opponent's move and updates the bot's own board.
   * @param x The x coordinate attacked by the opponent.
   * @param y The y coordinate attacked by the opponent.
   */
  turn(x: number, y: number): void {
    if (this.myStrategy.isHit(x, y)) {
      this.myBoard.board[x]![y] = State.Hit;
      const sunk = this.myStrategy.isSunk(this.myBoard.board);
      if (sunk) {
        for (const cell of this.myStrategy.getCells(sunk)) {
          this.myBoard.board[cell.x]![cell.y] = State.Sunk;
        }
      }
    }
  }
}
